// <auto-generated />
using System;
using BTCPayServer.Plugins.Galoy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTCPayServer.Plugins.Galoy.Migrations
{
    [DbContext(typeof(MyPluginDbContext))]
    partial class MyPluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Galoy")
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("BTCPayServer.Plugins.Galoy.Data.PluginData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PluginRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
